### PR TITLE
Updated lodash and changed outdated 'contains' to 'includes'

### PR DESCRIPTION
**Pull request by cepko33**

### CODE REVIEW

**Comment by tglines** [comment]
@shama any way we can get lodash bumped?

**Comment by shama** [comment]
Thanks for the ping!

**Comment by alexeyraspopov** [comment]
@shama are you able to push `v1.0.1` as well? Thanks!

**Comment by tglines** [comment]
@shama +1 for @alexeyraspopov 's suggestion.

**Comment by chaenu** [comment]
@shama +1 for @alexeyraspopov 's suggestion.

**Pull request merged**
