### PR TITLE
Expose hostname parameter of tiny-lr

### PR DESCRIPTION
**Pull request by timothykang**
Server.listen() gained optional hostname parameter in v0.1.2 release. (https://github.com/mklabs/tiny-lr/commit/e95c8e52b412e479b53bf277a837c2adf799a0d3)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why is this needed?

The merge conflict needs to be fixed.

**Comment by timothykang** [comment]
The tiny-lr server listens on all addresses (including externally) by default if a host isn't specified, which for development is usually unnecessary and possibly even insecure.

Existing behavior is preserved if the additional option is omitted, so there would be no difference to existing users.

**Comment by sindresorhus** [comment]
Lgtm.

@shama => merge?

**Comment by shama** [comment]
Thanks!

**Pull request merged**
