### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by ntwb**
Pull request only updates dependencies not covered by existing semver declared version ranges.

• Not sure why https://github.com/gruntjs/grunt-contrib-watch/pull/474 was closed as this in one of the reasons I've created this pull request.

• Also doesn't touch the Gaze dependency mentioned in https://github.com/gruntjs/grunt-contrib-watch/pull/412

The same two tests fail before and after updating the dependencies:
```
ERROR
>> Message: Task should have been interrupted 2 times.
>> Error: false == true
>> at Object.ok (node_modules/nodeunit/lib/types.js:83:39)
>> at /Users/netweb/dev/github-ntwb-grunt-contrib-watch/test/tasks/watch_test.js:143:12
>> at ChildProcess.<anonymous> (test/tasks/helper.js:84:7)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

>> Message: Only the last time should be working (without interruption)
>> Error: null == true
>> at Object.ok (node_modules/nodeunit/lib/types.js:83:39)
>> at /Users/netweb/dev/github-ntwb-grunt-contrib-watch/test/tasks/watch_test.js:145:12
>> at ChildProcess.<anonymous> (test/tasks/helper.js:84:7)
>> at emitTwo (events.js:87:13)
>> at ChildProcess.emit (events.js:172:7)
>> at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### CODE REVIEW

**Comment by ntwb** [comment]
Note: All tests pass on the NodeJS `0.10.x` tests, just fail on the `4` and `5`

**Comment by plynchnlm** [comment]
The reason I closed my pull request (#474) was that the master branch has an update to use tiny-lr 0.1.4, which has the update I needed for the qs dependency.

**Comment by lirantal** [comment]
@plynchnlm still 0.1.4 has a bad dependency version for `qa` which needs an update so this PR by @ntwb is just-fully opened and should be addressed.
 
@ntwb can you figure out why the tests fail?
I also suggest we open a PR just for `tiny-lr` to update solely where tests should probably pass easily. What do you think?

**Comment by lirantal** [comment]
@shama can we get some love here? :)

**Comment by ntwb** [comment]
I've just updated a pull request for `tiny-lr` https://github.com/mklabs/tiny-lr/pull/99

**Comment by ntwb** [comment]
See also a PR for `tiny-lr` and `qs` v6.x.x https://github.com/mklabs/tiny-lr/pull/101

**Comment by shama** [comment]
Thanks!

**Comment by lirantal** [comment]
great @shama. thank you :)

**Comment by lirantal** [comment]
@shama we should bump the version number now that you updated `package.json`
see my PR: https://github.com/gruntjs/grunt-contrib-watch/pull/495

**Pull request merged**
