### PR TITLE
Bump version due to dependencies update

### PR DESCRIPTION
**Pull request by lirantal**
Requires to update the module's version for projects to get the new packages

### CODE REVIEW

**Comment by shama** [comment]
@lirantal Could you explain why we should bump all the changes pending in `master` on a patch version? Also do you think it's a good idea to publish a version with tests failing?

**Comment by lirantal** [comment]
Hi @shama 

Those tests were failing before the merged PR to update the dependencies, right?
And secondly, you're right about the merge with `master` for incrementing a version, I didn't notice you have tagged versions for the module.

However, I do think that once the build is stable we increment either the patch or the minor versions for other projects who depend on this module will get the changes.

**Comment by XhmikosR** [comment]
This is bad practice. The tests should be fixed and also this shouldn't be a patch version.

**Comment by XhmikosR** [comment]
BTW @shama if there's any issue or something related to the changes we need to backport in contrib plugins (like the things we discussed the other time), please let me know.

**Comment by shama** [comment]
@lirantal Please take a look at http://semver.org/ and then look at the changes in `master` since the last release. Could you explain why you recommend publishing on a minor or patch version? Do you think those changes will break other people's builds on next install if we publish as a patch?

@XhmikosR Thanks!

**Comment by ntwb** [comment]
Heres the diff between `v0.6.1` and `master`: https://github.com/gruntjs/grunt-contrib-watch/compare/v0.6.1...master, there are enough changes albeit it only minor changes in ivereload.js/taskrun.js/taskrunner.js/watch.js to warrant a `minor` release in my opinion.

With that said though I agree that it should not be released until all the tests pass. (Currently tests pass on NodeJS v0.10.x, and fail on v4 & v5)

**Comment by ntwb** [comment]
See also #491

**Comment by lirantal** [comment]
@shama I'm aware of semver, but I didn't review `master` to trace back any changes. Looking at it now I still see a few commits related to spelling, jshints, and such which I don't believe to break the API but I didn't investigate more than a quick look and you know best.

At first I was under the impression that actually the master branch is already the last release tagged 0.6.1 and that the dependencies update is the new change.

So I take it back and we can close this PR as there are indeed tests that need to be resolved along with more commits on master rather than the package.json changes.

**Pull request closed without merging**
