### PR TITLE
More dependancy updates

### PR DESCRIPTION
**Pull request by ntwb**
Previously #483, see also #491, #495

### CODE REVIEW

**Comment by shama** [comment]
@ntwb Does this cause any other tests to fail?

**Comment by shama** [comment]
Looks like updating to `lodash >= 4` causes the tests to fail. @ntwb Are you willing to debug the issue?

**Comment by ntwb** [comment]
I'll have a try, not sure how far I'll get though

**Comment by shama** [comment]
Thanks @ntwb! Much appreciated!

**Comment by XhmikosR** [comment]
I'm gonna close this due to #500

**Pull request closed without merging**
