### PR TITLE
Update devDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by vladikoff** [comment]
Hm all ci exploded 🐊

**Comment by XhmikosR** [comment]
Yeah, in the nospawn test :/

Is there any related change in grunt 1.x?

**Comment by XhmikosR** [comment]
@vladikoff @shama: any ideas why the nospawn tests fail with the new grunt?

**Comment by shama** [comment]
The tests are failing here because the test helper this task uses has timing issues. So it's not specifically because of grunt 1.0.1 but the slight changes in timing breaks that test. It's been on my list to replace that test helper but I want to propose standalone tasks that can be tested more directly. Then this bad test helper can be removed.

I'm fine to remove this and walk around the timing issue in the meantime though. Thanks @XhmikosR!

**Pull request merged**
